services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.3
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
    #  - TZ=Etc/UTC
    #  - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - ~/containerc/jellyfin:/config
    #  - /path/to/tvseries:/data/tvshows
    #  - /path/to/movies:/data/movies
    ports:
      - 8096:8096
    #  - 8920:8920 #optional
    #  - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional
    restart: unless-stopped
